# Copyright (c) 2023 Joseph Hale
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---  # Denotes the start of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395
name: SixRooms
main: dev.lecya.six_rooms.SixRooms
version: 0.1.0
depend: [PlasmoVoice, WorldEdit]
api-version: 1.21
commands:
  sixrooms:
    description: Управление регистрацией и запуском игры
    usage: /sixrooms open|join|leave|start|cancel|status|phone|vote|exclude
    aliases: [sr, rooms]
permissions:
  sixrooms.admin:
    default: op
... # Denotes the end of this YAML document. https://yaml.org/spec/1.2/spec.html#id2760395
